# Generated by Django 5.2 on 2025-06-03 19:26

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categ_producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='MetodoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarjeta_nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Provedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.TextField(blank=True, null=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TipoPago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_pago', models.CharField(max_length=50)),
                ('tipo_logo', models.ImageField(upload_to='logos_pago/')),
                ('alias', models.CharField(blank=True, max_length=100, null=True)),
                ('cbu', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factura',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero_factura', models.CharField(max_length=10)),
                ('fecha', models.DateField()),
                ('nombre_cliente', models.CharField(max_length=255)),
                ('apellido_cliente', models.CharField(max_length=255)),
                ('domicilio', models.CharField(blank=True, max_length=255, null=True)),
                ('cuil', models.CharField(blank=True, max_length=20, null=True)),
                ('iva', models.CharField(blank=True, max_length=50, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('detalle_productos', models.TextField(default='Sin detalles')),
                ('imagen_factura', models.ImageField(blank=True, null=True, upload_to='factura_images/')),
                ('dni_cliente', models.CharField(blank=True, max_length=20, null=True)),
                ('vendedor', models.CharField(default='Sin asignar', max_length=100)),
                ('descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_descuento', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('estado_credito', models.CharField(default='Cuenta Corriente', max_length=50)),
                ('interes', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('total_con_interes', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('cuotas', models.IntegerField(default=0)),
                ('cuota_mensual', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('tarjeta_nombre', models.CharField(blank=True, max_length=50, null=True)),
                ('tarjeta_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('numero_tiket', models.CharField(blank=True, max_length=50, null=True)),
                ('estado_entrega', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptado', 'Aceptado'), ('rechazado', 'Rechazado')], default='pendiente', max_length=10, verbose_name='Estado de entrega')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='facturas', to='CarritoApp.metodopago', verbose_name='Método de pago')),
            ],
        ),
        migrations.CreateModel(
            name='CuentaCorriente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_factura', models.CharField(max_length=10)),
                ('descripcion', models.TextField()),
                ('fecha_cuota', models.DateField()),
                ('total_con_interes', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cuota_total', models.IntegerField(default=0)),
                ('cuota_paga', models.IntegerField(default=0)),
                ('cuota_debe', models.IntegerField(default=0)),
                ('cuota_suma', models.IntegerField(default=0)),
                ('imp_mensual', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('imp_cuota_pagadas', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('entrega_cta', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('tarjeta_nombre', models.CharField(blank=True, max_length=255, null=True)),
                ('tarjeta_numero', models.CharField(blank=True, max_length=20, null=True)),
                ('interes_aplicado', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuenta_corriente', to='CarritoApp.factura')),
                ('metodo_pago', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarritoApp.metodopago')),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_producto', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('nombre_producto', models.CharField(default='Nombre del producto', max_length=255)),
                ('descripcion', models.TextField(default='Sin descripción')),
                ('imagen', models.ImageField(upload_to='productos/')),
                ('stock', models.PositiveIntegerField(default=0)),
                ('precio', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('categoria', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='CarritoApp.categ_producto')),
            ],
        ),
        migrations.CreateModel(
            name='FacturaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.factura')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.producto')),
            ],
        ),
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField()),
                ('precio_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('factura_compra', models.CharField(max_length=100)),
                ('fecha_compra', models.DateField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.producto')),
                ('provedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='CarritoApp.provedor')),
            ],
        ),
        migrations.CreateModel(
            name='Venta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('precio', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='CarritoApp.producto')),
                ('usuario', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
