# Generated by Django 5.2 on 2025-06-05 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='metodo_pago_manual',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Método de pago (manual)'),
        ),
    ]
