# Generated by Django 5.2 on 2025-06-10 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0002_factura_metodo_pago_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='metodopago',
            name='tarjeta_cuota',
            field=models.CharField(choices=[('Sí', 'Sí'), ('No', 'No')], default='No', max_length=10),
        ),
        migrations.AddField(
            model_name='metodopago',
            name='tarjeta_porcentaje',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
    ]
