# Generated by Django 5.2 on 2025-06-10 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0003_metodopago_tarjeta_cuota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='metodopago',
            name='tarjeta_cuota',
            field=models.IntegerField(default=0),
        ),
    ]
