# Generated by Django 5.2 on 2025-06-10 23:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0004_alter_metodopago_tarjeta_cuota'),
    ]

    operations = [
        migrations.CreateModel(
            name='CuotaInteres',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad_cuotas', models.IntegerField()),
                ('porcentaje_interes', models.DecimalField(decimal_places=2, max_digits=5)),
                ('metodo_pago', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuotas_interes', to='CarritoApp.metodopago')),
            ],
        ),
    ]
