# Generated by Django 5.2 on 2025-08-18 19:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CarritoApp', '0005_cuotainteres'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MensajeCliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=80)),
                ('nombre', models.CharField(max_length=80)),
                ('pedido', models.CharField(max_length=255, verbose_name='Mensaje / Pedido')),
                ('email_contacto', models.EmailField(blank=True, max_length=254, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('respondido', models.BooleanField(default=False)),
                ('respuesta', models.TextField(blank=True, null=True)),
                ('respondido_en', models.DateTimeField(blank=True, null=True)),
                ('activo', models.BooleanField(default=True)),
                ('creado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_enviados', to=settings.AUTH_USER_MODEL)),
                ('respondido_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensajes_respondidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
    ]
