# Generated by Django 5.2 on 2025-04-16 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dni_usuario', models.CharField(blank=True, max_length=15, null=True)),
                ('nombre', models.CharField(max_length=100)),
                ('edad', models.IntegerField()),
                ('especie', models.CharField(choices=[('Perro', 'Perro'), ('Gato', 'Gato'), ('Otro', 'Otro')], max_length=50)),
                ('descripcion', models.TextField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen1', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen2', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen3', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen4', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('imagen5', models.ImageField(blank=True, null=True, upload_to='mascotas/')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Informe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('informe', models.TextField()),
                ('foto_imagen', models.ImageField(blank=True, null=True, upload_to='informes/')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('mascota', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mascota.mascota')),
            ],
        ),
    ]
